site_name: Capability API Governance
nav:
  - Overview: index.md
  - Onboarding: onboarding.md
  - Architecture: architecture.md
  - Governance: governance.md
  - Policy Verification: policy-verification/latest.md
  - Mermaid Test: test-mermaid.md
plugins:
  - techdocs-core
  - kroki:
      server_url: https://kroki.io
      http_method: POST
markdown_extensions:
  - pymdownx.superfences
