site_name: Capability API Governance
nav:
  - Overview: index.md
  - Onboarding: onboarding.md
  - Architecture: architecture.md
  - Governance:
      - Policy Verification: policy-verification/latest.md
plugins:
  - techdocs-core
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ''
