site_name: Capability API Governance
nav:
  - Overview: index.md
  - Onboarding: onboarding.md
  - Architecture: architecture.md
  - Governance:
      - Policy Verification: policy-verification/latest.md
plugins:
  - techdocs-core
  - mermaid2
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom ''
